'''

We are going to write a program that generates a random number and asks the user to 
guess it.

If the player's guess is higher than the actual number, the program displays “Lower 
number please”. Similarly, if the user's guess is too low, the program prints “higher 
number please” When the user guesses the correct number, the program displays the 
number of guesses the player used to arrive at the number. 

Hint: Use the random module

'''

import random 

computer = random.randint(0,100)

print("Welcome to the \"The Perfect Guess Game\"  ")
count = 0
flag=True
while(flag):
    user = int(input("Enter any number from 0 To 100 :-  "))
    if(user>=0 and user<=100):
       if(user>computer):
        print(f"{user} is Greater than actual number Generated by Computer :-  {computer}")
        count+=1
        print(f"Number of times tried is :- {count}")
       elif(user<computer):
        print(f"{user} is Less than the actual number Generated by Computer :- {computer}")
        count+=1
        print(f"Number of times tried is :-  {count}")
       else:
        print(f"{user} is Equal's to the Actual Number Generated by the Computer {computer} . # You have Guessed Correctly . Congrats 🥳")
        count+=1
        print(f"Number of times tried is :- {count} ")
        break
    else:
      print("Invalid Input . Please enter the required value.")
      count+=1



'''
Output :- 

Welcome to the "The Perfect Guess Game"  
Enter any number from 0 To 100 :-  3
3 is Less than the actual number Generated by Computer :- 37
Number of times tried is :-  1
Enter any number from 0 To 100 :-  34
34 is Less than the actual number Generated by Computer :- 37
Number of times tried is :-  2
Enter any number from 0 To 100 :-  37
37 is Equal's to the Actual Number Generated by the Computer 37 . # You have Guessed Correctly . Congrats 🥳
Number of times tried is :- 3 

'''